/* ============================================================
   CATÁLOGO DE PRODUCTOS — Maju Shoes
   ------------------------------------------------------------
   ORDEN: los productos de la misma marca van juntos. Al agregar
   uno nuevo, ponlo al lado de los de su marca, no al final.
   El orden de esta lista es el orden en que se ven en la página.

   Para agregar un producto, copia un bloque y cambia los datos.
   Cada producto es un objeto:

   {
     id:       texto único, sin espacios (se usa para el carrito)
     name:     nombre que ve el cliente
     gender:   "Hombre" | "Mujer" | "Unisex"  (para los filtros;
               los Unisex aparecen al filtrar Hombre y también Mujer)
     price:    precio en pesos, SIN puntos (175000 = $175.000)
     sizes:    todas las tallas que maneja la referencia
     soldOut:  tallas agotadas por el momento. Se siguen mostrando,
               pero tachadas y sin poder agregarlas al carrito.
               Déjalo como [] cuando haya de todas las tallas.
     tag:      etiqueta ("Nuevo", "Últimas tallas", ...). Se deja
               vacía ("") salvo que la tienda pida ponerla.
     art:      dibujo de muestra: "runner" | "boot" | "classic" | "slipon"
     image:    RUTA A LA FOTO REAL, ej. "img/nike-dn.jpeg".
               Mientras esté vacío ("") se muestra el dibujo de muestra.
   }
   ============================================================ */

const PRODUCTS = [
  {
    id: "nike-dn",
    name: "Nike DN",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [38, 39, 41, 42, 43, 44],
    tag: "",
    art: "runner",
    image: "img/nike-dn.jpeg",
  },
  {
    /* Misma referencia que el anterior, negro con detalles rojos */
    id: "nike-dn-negro",
    name: "Nike DN",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-dn-negro.jpeg",
  },
  {
    /* Misma referencia, lila con suela blanca */
    id: "nike-dn-lila",
    name: "Nike DN",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-dn-lila.jpeg",
  },
  {
    /* Misma referencia, coral con negro */
    id: "nike-dn-coral",
    name: "Nike DN",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-dn-coral.jpeg",
  },
  {
    /* Misma referencia, rojo con negro */
    id: "nike-dn-rojo-negro",
    name: "Nike DN",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-dn-rojo-negro.jpeg",
  },
  {
    /* Misma referencia, rojo completo */
    id: "nike-dn-rojo",
    name: "Nike DN",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-dn-rojo.jpeg",
  },
  {
    id: "nike-tn-negro",
    name: "Nike TN",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-tn-negro.jpeg",
  },
  {
    /* Misma referencia que el anterior, en otro color (blanco) */
    id: "nike-tn-blanco",
    name: "Nike TN",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-tn-blanco.jpeg",
  },
  {
    /* Misma referencia, todo negro */
    id: "nike-tn-negro-total",
    name: "Nike TN",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-tn-negro-total.jpeg",
  },
  {
    /* Misma referencia, todo blanco */
    id: "nike-tn-blanco-total",
    name: "Nike TN",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-tn-blanco-total.jpeg",
  },
  {
    /* Misma referencia, blanco con rosado y turquesa */
    id: "nike-tn-south-beach",
    name: "Nike TN",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-tn-south-beach.jpeg",
  },
  {
    /* Misma referencia, blanco con paloma rosada */
    id: "nike-tn-blanco-rosado",
    name: "Nike TN",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-tn-blanco-rosado.jpeg",
  },
  {
    id: "nike-air-max-90",
    name: "Nike Air Max 90",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-air-max-90.jpeg",
  },
  {
    id: "nike-air-max-95",
    name: "Nike Air Max 95",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-air-max-95.jpeg",
  },
  {
    id: "nike-air-max-moto-2k",
    name: "Nike Air Max Moto 2k",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-air-max-moto-2k.jpeg",
  },
  {
    /* Beige con gamuza gris y suela caramelo */
    id: "nike-air-max-sc-beige",
    name: "Nike Air Max SC",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-air-max-sc-beige.jpeg",
  },
  {
    /* Misma referencia, blanco con rosado */
    id: "nike-air-max-sc-rosado",
    name: "Nike Air Max SC",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-air-max-sc-rosado.jpeg",
  },
  {
    id: "nike-air-max-plus",
    name: "Nike Air Max Plus",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-air-max-plus.jpeg",
  },
  {
    id: "nike-air-force-one",
    name: "Nike Air Force One",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/nike-air-force-one.jpeg",
  },
  {
    /* Misma referencia, blanco con paloma morada */
    id: "nike-air-force-one-morado",
    name: "Nike Air Force One",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/nike-air-force-one-morado.jpeg",
  },
  {
    /* Misma referencia, paloma rosada y suela celeste */
    id: "nike-air-force-one-rosado",
    name: "Nike Air Force One",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/nike-air-force-one-rosado.jpeg",
  },
  {
    id: "nike-sb-jarritos",
    name: "Nike SB Jarritos",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/nike-sb-jarritos.jpeg",
  },
  {
    /* Blanco con paloma negra y suela caramelo */
    id: "nike-dunk-low",
    name: "Nike Dunk Low",
    gender: "Unisex",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/nike-dunk-low.jpeg",
  },
  {
    id: "nike-free",
    name: "Nike Free",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-free.jpeg",
  },
  {
    id: "nike-p-6000",
    name: "Nike P-6000",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-p-6000.jpeg",
  },
  {
    /* Misma referencia, toda blanca */
    id: "nike-p-6000-blanco",
    name: "Nike P-6000",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-p-6000-blanco.jpeg",
  },
  {
    /* Blanco con gris */
    id: "nike-vomero-5",
    name: "Nike Vomero 5",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-vomero-5.jpeg",
  },
  {
    /* Misma referencia, color hueso */
    id: "nike-vomero-5-beige",
    name: "Nike Vomero 5",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-vomero-5-beige.jpeg",
  },
  {
    /* Gris oscuro con suela crema */
    id: "nike-v2k-run",
    name: "Nike V2K Run",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-v2k-run.jpeg",
  },
  {
    /* Blanco con café y paloma vinotinto */
    id: "nike-initiator",
    name: "Nike Initiator",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-initiator.jpeg",
  },
  {
    /* Negro con suela blanca */
    id: "nike-zoom-negro",
    name: "Nike Zoom",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-zoom-negro.jpeg",
  },
  {
    /* Misma referencia, toda blanca */
    id: "nike-zoom-blanco",
    name: "Nike Zoom",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-zoom-blanco.jpeg",
  },
  {
    /* Negro con suela blanca y la carita en el talón */
    id: "nike-carita",
    name: "Nike Carita",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-carita.jpeg",
  },
  {
    id: "nike-shox",
    name: "Nike Shox",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/nike-shox.jpeg",
  },
  {
    id: "jordan-11",
    name: "Jordan 11",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/jordan-11.jpeg",
  },
  {
    /* Misma referencia, negro con Jumpman turquesa y suela traslúcida */
    id: "jordan-11-turquesa",
    name: "Jordan 11",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "boot",
    image: "img/jordan-11-turquesa.jpeg",
  },
  {
    /* Jordan 1 Mid, blanco con plateado metalizado */
    id: "jordan-1",
    name: "Jordan 1",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/jordan-1.jpeg",
  },
  {
    /* Caña baja, blanco con gris y Jumpman dorado */
    id: "jordan-1-low",
    name: "Jordan 1 Low",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/jordan-1-low.jpeg",
  },
  {
    id: "puma-gv-special",
    name: "Puma GV Special",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/puma-gv-special.jpeg",
  },
  {
    id: "skechers-dlux",
    name: "Skechers D'Lux",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/skechers-dlux.jpeg",
  },
  {
    /* Misma referencia que el anterior, en otro color (beige) */
    id: "skechers-dlux-beige",
    name: "Skechers D'Lux",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/skechers-dlux-beige.jpeg",
  },
  {
    /* Negro con tres franjas blancas y suela blanca */
    id: "adidas-supernova",
    name: "Adidas Supernova",
    gender: "Unisex",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/adidas-supernova.jpeg",
  },
  {
    /* Blanco con franjas lila y detalles verde limón */
    id: "adidas-adizero-evo-sl",
    name: "Adidas Adizero Evo SL",
    gender: "Unisex",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/adidas-adizero-evo-sl.jpeg",
  },
  {
    id: "adidas-bounce",
    name: "Adidas Bounce",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/adidas-bounce.jpeg",
  },
  {
    /* Misma referencia, negro con franjas grandes y suela blanca */
    id: "adidas-bounce-franjas",
    name: "Adidas Bounce",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/adidas-bounce-franjas.jpeg",
  },
  {
    /* Misma referencia, negro con suela blanca acolchada */
    id: "adidas-bounce-suela-blanca",
    name: "Adidas Bounce",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/adidas-bounce-suela-blanca.jpeg",
  },
  {
    /* Tejido negro con tres franjas blancas */
    id: "adidas-swift",
    name: "Adidas Swift",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/adidas-swift.jpeg",
  },
  {
    id: "adidas-repetitor",
    name: "Adidas Repetitor",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/adidas-repetitor.jpeg",
  },
  {
    /* Misma referencia, negro con franjas y suela blancas */
    id: "adidas-repetitor-blanco",
    name: "Adidas Repetitor",
    gender: "Unisex",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/adidas-repetitor-blanco.jpeg",
  },
  {
    id: "adidas-terrex-blanco",
    name: "Adidas Terrex",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/adidas-terrex-blanco.jpeg",
  },
  {
    /* Misma referencia que el anterior, en otro color (beige) */
    id: "adidas-terrex-beige",
    name: "Adidas Terrex",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/adidas-terrex-beige.jpeg",
  },
  {
    /* Misma referencia, en negro con suela blanca */
    id: "adidas-terrex-negro",
    name: "Adidas Terrex",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/adidas-terrex-negro.jpeg",
  },
  {
    /* Misma referencia, en negro con suela gris y cordones naranjas */
    id: "adidas-terrex-gris",
    name: "Adidas Terrex",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/adidas-terrex-gris.jpeg",
  },
  {
    id: "bape",
    name: "Bape",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/bape.jpeg",
  },
  {
    id: "calvin-klein",
    name: "Calvin Klein",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/calvin-klein.jpeg",
  },
  {
    /* Plataforma, blanco con negro */
    id: "calvin-klein-plataforma-negro",
    name: "Calvin Klein",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/calvin-klein-plataforma-negro.jpeg",
  },
  {
    /* Misma plataforma que el anterior, toda blanca */
    id: "calvin-klein-plataforma-blanco",
    name: "Calvin Klein",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/calvin-klein-plataforma-blanco.jpeg",
  },
  {
    /* Runner negro con monograma CK */
    id: "calvin-klein-monograma",
    name: "Calvin Klein",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/calvin-klein-monograma.jpeg",
  },
  {
    id: "new-balance-1906",
    name: "New Balance 1906",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/new-balance-1906.jpeg",
  },
  {
    /* Misma referencia que el anterior, en otro color (gris) */
    id: "new-balance-1906-gris",
    name: "New Balance 1906",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/new-balance-1906-gris.jpeg",
  },
  {
    /* Blanco con azul oscuro y plateado */
    id: "new-balance-530",
    name: "New Balance 530",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/new-balance-530.jpeg",
  },
  {
    /* Blanco con detalles verdes; falta confirmar el número del modelo */
    id: "new-balance",
    name: "New Balance",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/new-balance.jpeg",
  },
  {
    id: "michael-kors",
    name: "Michael Kors",
    gender: "Unisex",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/michael-kors.jpeg",
  },
  {
    /* Misma marca, en cuero negro con suela blanca */
    id: "michael-kors-negro",
    name: "Michael Kors",
    gender: "Unisex",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/michael-kors-negro.jpeg",
  },
  {
    id: "clemont",
    name: "Clemont",
    gender: "Unisex",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/clemont.jpeg",
  },
  {
    /* Misma referencia que el anterior, con suela blanca */
    id: "clemont-blanco",
    name: "Clemont",
    gender: "Unisex",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/clemont-blanco.jpeg",
  },
  {
    id: "coach",
    name: "Coach",
    gender: "Unisex",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/coach.jpeg",
  },
  {
    /* Misma marca, todo negro con monograma */
    id: "coach-negro",
    name: "Coach",
    gender: "Unisex",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/coach-negro.jpeg",
  },
  {
    /* Plataforma blanca, monograma negro charolado */
    id: "coach-plataforma-negro",
    name: "Coach",
    gender: "Mujer",
    price: 175000,
    sizes: [35, 36, 37, 38, 39, 40],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/coach-plataforma-negro.jpeg",
  },
  {
    id: "boss-negro",
    name: "Boss",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/boss-negro.jpeg",
  },
  {
    /* Otra referencia Boss: cuero con monograma y suela blanca */
    id: "boss-monograma",
    name: "Boss",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/boss-monograma.jpeg",
  },
  {
    /* Otra referencia Boss: nubuck negro con suela dentada */
    id: "boss-nubuck",
    name: "Boss",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/boss-nubuck.jpeg",
  },
  {
    /* Otra referencia Boss: malla negra con suela gris */
    id: "boss-malla",
    name: "Boss",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "runner",
    image: "img/boss-malla.jpeg",
  },
  {
    /* Cuero texturizado con suela negra y talón plateado */
    id: "boss-suela-negra",
    name: "Boss",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/boss-suela-negra.jpeg",
  },
  {
    id: "oakley-blanco",
    name: "Oakley",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/oakley-blanco.jpeg",
  },
  {
    /* Misma referencia que el anterior, todo negro */
    id: "oakley-negro",
    name: "Oakley",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/oakley-negro.jpeg",
  },
  {
    /* Misma marca, en blanco y gris con suela caramelo */
    id: "oakley-gris",
    name: "Oakley",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/oakley-gris.jpeg",
  },
  {
    id: "off-white",
    name: "Off White",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/off-white.jpeg",
  },
  {
    /* Monograma negro con gris y charol */
    id: "creative",
    name: "Creative",
    gender: "Hombre",
    price: 175000,
    sizes: [38, 39, 40, 41, 42, 43, 44],
    soldOut: [],
    tag: "",
    art: "classic",
    image: "img/creative.jpeg",
  },
];

/* Filtros del catálogo */
const FILTERS = {
  todos: "Todos",
  hombre: "Hombre",
  mujer: "Mujer",
};
